spring:
  my:
    nickname: prod USER!!!
  datasource:
    username: ${DB_USERNAME}  # 환경변수 DB_USERNAME을 사용
    password: ${DB_PASSWORD}  # 환경변수 DB_PASSWORD를 사용
    url: jdbc:postgresql://ippo-db:5432/ippo_db  # 데이터베이스 URL
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul  # 한국 시간대 설정
        format_sql: true  # 문자열이 아닌 불리언 값으로 변경
        dialect: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL Dialect 설정
    hibernate:
      # ddl-auto: validate
      ddl-auto: update
    show-sql: true  # 문자열이 아닌 불리언 값으로 변경
  config:
    import: "optional:classpath:openai.properties"

  data:
    redis:
      host: ippo-redis
      port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


