spring:
  my:
    nickname: DEV USER!!!
  datasource:
    username: postgres
    password: i4mz1234
    url: jdbc:postgresql://13.59.165.113:5432/postgres
    hikari:
      maximum-pool-size: "4"
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul # 여기에 한국 시간대 설정을 추가합니다.
          lob:
            non_contextual_creation: "true"
        format_sql: "true"
        dialect: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL Dialect 설정
    hibernate:
      ddl-auto: validate
    show-sql: "true"
  #Redis DB 연동
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
