# JDK 17을 포함하는 기본 이미지
FROM openjdk:17-slim as build

# 프로젝트 파일 복사
# 현재 Dockerfile 위치가 기준이므로, 상대 경로를 사용합니다.
COPY ./ /app/

# 작업 디렉토리 설정
WORKDIR /app

# Gradle Wrapper 실행 권한 부여
RUN chmod +x ./gradlew

# Gradle Wrapper를 이용해 애플리케이션 빌드 및 패키징
RUN ./gradlew build --no-daemon

# 실행을 위한 JDK 이미지
FROM openjdk:17-slim

# 빌드 단계에서 생성된 실행 가능한 JAR 파일을 복사
# build 스테이지의 결과물을 최종 이미지로 복사합니다.
COPY --from=build /app/build/libs/*.jar /app/app.jar

# 애플리케이션 실행
ENTRYPOINT ["java","-jar", "/app/app.jar"]
