# Node.js를 이용해 Node 앱을 빌드하기 위한 기본 이미지
FROM node:20.10.0 as build

# 작업 디렉토리 설정
WORKDIR /app

# package.json과 package-lock.json 파일 복사
COPY package*.json ./

# 의존성 설치
RUN npm install

# 애플리케이션 소스 복사
COPY ./ /app/

# NodeExpress 애플리케이션 빌드
RUN npm run build

# 애플리케이션 실행을 위한 포트 설정
EXPOSE 3001

# 애플리케이션 실행
CMD ["node", "src/index.js"]
