# Node.js를 이용해 React 앱을 빌드하기 위한 기본 이미지
FROM node:20.10.0 as build

ARG REACT_APP_TO_GLIM

# 작업 디렉토리 설정
WORKDIR /app

# package.json 및 package-lock.json 파일 복사
COPY package*.json ./

RUN echo "REACT_APP_TO_GLIM=${REACT_APP_TO_GLIM}" >> .env

# 필요한 node modules 설치
RUN npm install

# 소스 코드 복사
COPY . .


# React 애플리케이션 빌드
RUN npm run build

# 환경변수 보호
RUN rm .env

# Nginx를 사용해 빌드된 정적 파일 제공
FROM nginx:stable

# 수정된 부분: 빌드된 파일들을 /usr/share/nginx/html/dist 경로에 복사
COPY --from=build /app/build /usr/share/nginx/html

# /etc/nginx/conf.d/ 디렉토리를 생성 (만약 없을 경우)
RUN mkdir -p /etc/nginx/conf.d

# 기본 nginx 설정 파일을 삭제한다. (custom 설정과 충돌 방지)
RUN rm /etc/nginx/conf.d/default.conf

# Nginx 설정 파일을 복사
COPY nginx/ippo.conf /etc/nginx/conf.d


EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]